### ISSUE TITLE
Installation from source on PyPI fails with ValueError

### ISSUE THREAD

**Issue by cgohlke** [Unidata/cftime#103]
The sdist archive, `cftime-1.0.3.1.tar.gz`, on [PyPI](https://pypi.org/project/cftime/#files) contains an absolute path in `cftime.egg-info\SOURCES.txt` such that installation from source fails:

```
<snip>
running egg_info
writing cftime.egg-info\PKG-INFO
writing dependency_links to cftime.egg-info\dependency_links.txt
writing requirements to cftime.egg-info\requires.txt
writing top-level names to cftime.egg-info\top_level.txt
reading manifest file 'cftime.egg-info\SOURCES.txt'
Traceback (most recent call last):
  File "setup.py", line 122, in <module>
    'License :: OSI Approved'])
  File "X:\Python36\lib\site-packages\setuptools\__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "X:\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "X:\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "X:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "X:\Python36\lib\site-packages\wheel\bdist_wheel.py", line 224, in run
    self.run_command('install')
  File "X:\Python36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "X:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "X:\Python36\lib\site-packages\setuptools\command\install.py", line 61, in run
    return orig.install.run(self)
  File "X:\Python36\lib\distutils\command\install.py", line 557, in run
    self.run_command(cmd_name)
  File "X:\Python36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "X:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "X:\Python36\lib\site-packages\setuptools\command\install_egg_info.py", line 34, in run
    self.run_command('egg_info')
  File "X:\Python36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "X:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "X:\Python36\lib\site-packages\setuptools\command\egg_info.py", line 296, in run
    self.find_sources()
  File "X:\Python36\lib\site-packages\setuptools\command\egg_info.py", line 303, in find_sources
    mm.run()
  File "X:\Python36\lib\site-packages\setuptools\command\egg_info.py", line 534, in run
    self.add_defaults()
  File "X:\Python36\lib\site-packages\setuptools\command\egg_info.py", line 577, in add_defaults
    self.read_manifest()
  File "X:\Python36\lib\site-packages\setuptools\command\sdist.py", line 199, in read_manifest
    self.filelist.append(line)
  File "X:\Python36\lib\site-packages\setuptools\command\egg_info.py", line 476, in append
    path = convert_path(item)
  File "X:\Python36\lib\distutils\util.py", line 125, in convert_path
    raise ValueError("path '%s' cannot be absolute" % pathname)
ValueError: path '/private/tmp/cftime/cftime/_cftime.c' cannot be absolute
```

**Comment by jswhit** [comment]
This is because 'sdist' is cythonizing the .pyx file.  This was supposedly fixed - I'll fix it again and re-upload a source tar file.

**Comment by jswhit** [comment]
Apparently pypi doesn't let you re-upload files with the same name. I will have to make a new release (1.0.3.2).  SIgh.

**Comment by jswhit** [comment]
1.0.3.3 release created on pypi, source tarball works with this one.

**Comment by cgohlke** [comment]
Thank you!

**Comment by cgohlke** [comment]
Sorry, now there's `/Users/jsw/python/cftime/cftime/_cftime.c` in `SOURCES.txt`:

```
ValueError: path '/Users/jsw/python/cftime/cftime/_cftime.c' cannot be absolute
```

**Comment by jswhit** [comment]
OMG - this is really annoying.  Turns out that if _cftime.c was generated by a previous cythonize, it gets included in SOURCES.txt.  Have to make sure that `setup.py clean_cython` is run before `sdist`.

**Comment by jswhit** [comment]
OK, now it's really fixed (promise!). Version 1.0.3.4 on pypi.  Thanks for your patience.
