### ISSUE TITLE
Missing wheels for macosx-cp38 for release 1.1.1

### ISSUE THREAD

**Issue by s-weigand** [Unidata/cftime#150]
Since the new release of `cftime`, we found that our CI (github actions) is failing the python 3.8 macosx tests, when trying to install `cftime`. 

```
Collecting cftime
  Downloading cftime-1.1.1.tar.gz (48 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/runner/hostedtoolcache/Python/3.8.2/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-wakqznyj/cftime/setup.py'"'"'; __file__='"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-wakqznyj/cftime/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-wakqznyj/cftime/pip-egg-info
         cwd: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-wakqznyj/cftime/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-wakqznyj/cftime/setup.py", line 5, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
```

My guess is that this is due to the [missing wheels for  macosx-cp38](https://pypi.org/project/cftime/#files).

Thanks in advance 😄

**Comment by ocefpaf** [comment]
This was fixed in #149 BTW. We need a new release.

(Wheels would also help.)

**Comment by s-weigand** [comment]
Oh I didn't see #149 since it was already closed.
Thanks for the info 😄

**Comment by jswhit** [comment]
wheel macos x 3.8 wheel for 1.1.1 is now uploaded to pypi.
A new release (1.1.1.1) with PR #149 will be up later today.

**Comment by matthew-brett** [comment]
Great - thanks.

**Comment by jswhit** [comment]
New release is up

**Comment by s-weigand** [comment]
Our CI tests pass again!
Thanks a lot ❤️
