### ISSUE TITLE
Python 3.10 macOS universal2 wheel is not universal (does not contain arm64 architecture) 

### ISSUE THREAD

**Issue by burnpanck** [Unidata/cftime#264]
Installing on a M1 mac with python 3.10 using pip succeeds.
```
$ pip install cftime    
Collecting cftime
  Using cached cftime-1.5.1.1-cp310-cp310-macosx_10_9_universal2.whl (222 kB)
Requirement already satisfied: numpy in /Users/yves/.pyenv/versions/3.10.0/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from cftime) (1.21.4)
Installing collected packages: cftime
Successfully installed cftime-1.5.1.1
```

However, the resulting install is broken:
```
$ python -c "import sys;print(sys.version);import cftime" 
3.10.0 (default, Dec 17 2021, 20:54:45) [Clang 13.0.0 (clang-1300.0.29.30)]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/yves/.pyenv/versions/3.10.0/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cftime/__init__.py", line 1, in <module>
    from ._cftime import (datetime, real_datetime,
ImportError: dlopen(/Users/yves/.pyenv/versions/3.10.0/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cftime/_cftime.cpython-310-darwin.so, 0x0002): tried: '/Users/yves/.pyenv/versions/3.10.0/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cftime/_cftime.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_cftime.cpython-310-darwin.so' (no such file), '/usr/lib/_cftime.cpython-310-darwin.so' (no such file)
```

**Comment by jswhit** [comment]
experiment universal2 and arm64 wheels at https://github.com/MacPython/cftime-wheels/releases/tag/v1.5.1.1rel - if these are confirmed to work I will create a new pypi release.

**Comment by burnpanck** [comment]
For me, both of these wheels do work as expected. I just tested importing using `python -c "import sys;print(sys.version);import cftime"` as above, nothing else.

**Comment by jswhit** [comment]
working on 1.5.2 release now which will include those wheels....
