### ISSUE TITLE
`date2num` raises Exception with masked inputs

### ISSUE THREAD

**Issue by davidhassell** [Unidata/cftime#267]
Hello,

When using `cftime.date2num` with masked inputs I get a failure:

```python
>>> import cftime
>>> cftime.__version__
1.5.2
>>> import numpy as np
>>> a = [
    cftime.DatetimeGregorian(2000, 12, 1),
    cftime.DatetimeGregorian(2000, 12, 2),
    cftime.DatetimeGregorian(2000, 12, 3),
    cftime.DatetimeGregorian(2000, 12, 4),
]
>>> array = np.ma.array(a, mask=[True, False, True, False])
>>> out = cftime.date2num(array, units="days since 2000-12-01", calendar="standard")
Traceback (most recent call last):
  File "/home/david/cfunits_test.py", line 13, in <module>
    out = cftime.date2num(array, units="days since 2000-12-01", calendar="standard")
  File "src/cftime/_cftime.pyx", line 265, in cftime._cftime.date2num
  File "src/cftime/_cftime.pyx", line 362, in cftime._cftime.to_calendar_specific_datetime
AttributeError: 'MaskedConstant' object has no attribute 'year'
```
where as I expected to get:

```python
masked_array(data=[--, 1.0, --, 3.0],
             mask=[ True, False,  True, False],
       fill_value=1e+20)
```
I'm happy to provide a PR that would solve this, if you like (I already have tested some code that works ...).

Thanks, David

**Comment by jswhit2** [comment]
yes, please do create a PR
