### ISSUE TITLE
DateFromJulianDay : day is out of range for month

### ISSUE THREAD

**Issue by pelson** [Unidata/cftime#49]
The following was raised in https://github.com/SciTools/cf_units/issues/77:

```
>>> import cftime
>>> cftime.DateFromJulianDay(2450022.5, "standard")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cftime/_cftime.pyx", line 709, in cftime._cftime.DateFromJulianDay
ValueError: day is out of range for month
```

I haven't taken the time to dig further into this, but looks like reasonable input to the function.

When doing a bit of digging, I also tried:

```
>>> cftime.DateFromJulianDay(2450022.5, "standard", only_use_cftime_datetimes=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cftime/_cftime.pyx", line 709, in cftime._cftime.DateFromJulianDay
  File "cftime/_cftime.pyx", line 1759, in cftime._cftime.DatetimeGregorian.__init__
  File "cftime/_cftime.pyx", line 1903, in cftime._cftime.assert_valid_date
ValueError: invalid day number provided in cftime.DatetimeGregorian(1995, 10, 32, 23, 59, 59, 999952, -1, 1)
```

**Comment by jhamman** [comment]
Thanks @pelson for the report. This does seem like a bug.

**Comment by jswhit** [comment]
pull request #65 fixes this (by re-introducing an old bug fix that was somehow lost)

**Comment by jswhit** [comment]
fixed now in master, closing
