### ISSUE TITLE
Uninformative error message from _dateparse

### ISSUE THREAD

**Issue by aidanheerdegen** [Unidata/cftime#57]
`cftime._cftime._dateparse` returns quite opaque error messages that can lead to issues tracking down errors.

For example:

```python
>>> cftime._cftime._dateparse('days_since_1900-01-01')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cftime/_cftime.pyx", line 56, in cftime._cftime._dateparse
IndexError: list index out of range
```

The code assumes the string can be split by whitespace into two strings. In the above example it cannot.

**Comment by aidanheerdegen** [comment]
I have coded something up, but am having some trouble getting the tests to find the updated `cftime` package. Will do a PR when I get it sorted.
